# Задача 1

1. Найти имена, которые входят в первый список, но не входят во второй список
2. Найти имена, которые входят во второй список, но не входят в первый список
3. Найти имена, которые входят в оба списка
4. Найти имена, которые не входят в оба списка

In [1]:
list_1 = [
    'Светлана',
    'Мария',
    'Игорь',
    'Илья',
    'Олег'
]

In [7]:
list_2 = [
    'Светлана',
    'Иван',
    'Василиса',
    'Олег'
]

In [12]:
s1 = set(list_1)
s2 = set(list_2)


# 1. Найти имена, которые входят в первый список, но не входят во второй список
print (s1.difference(s2))

# 2. Найти имена, которые входят во второй список, но не входят в первый список
print (s2.difference(s1))

# 3. Найти имена, которые входят в оба списка
print (s1.intersection(s2))

# 4. Найти имена, которые не входят в оба списка
print (s1.symmetric_difference(s2))



{'Илья', 'Мария', 'Игорь'}
{'Иван', 'Василиса'}
{'Олег', 'Светлана'}
{'Игорь', 'Мария', 'Иван', 'Илья', 'Василиса'}


## Задача 2

Ниже задан словарь и заполнен значениями (это вымышленные ученики). В качестве ключей выступают номера телефонов, в качестве значений - словари с полной информацией о человеке. Необходимо сделать:
1. Вывести ФИО всех учеников (по одному в каждой строке). Выводить через for
2. Посчитать среднюю оценку по группе за каждый месяц (всего было 4 месяца - необходимо вывести 4 числа). Опять же, делаем из предположения, что в словаре может быть очень большое кол-во записей.
3. Удалить ученика с самой низкой средней оценкой. Посчитать п.2 по оставшимся.

In [136]:
# Имя
# Фамилия
# Пол
# Дата рождения
# Возраст


group = {
    '+79291111111':{
        'Имя':'Иван',
        'Фамилия':'Петров',
        'Пол':'м',
        'Дата рождения':'01-01-1991',
        'Возраст':23,
        'Итоговые оценки за месяц':(60, 65, 97, 40),
        'Итоговая контрольная':40.7,
    },
     '+79282222233':{
        'Имя':'Матвей',
        'Фамилия':'Васильев',
        'Пол':'м',
        'Дата рождения':'04-09-1996',
        'Возраст':20,
        'Итоговые оценки за месяц':(70, 75, 67, 40),
        'Итоговая контрольная':49.6,
    },
     '+79264443333':{
        'Имя':'Татьяна',
        'Фамилия':'Фоменко',
        'Пол':'ж',
        'Дата рождения':'01-01-1988',
        'Возраст':27,
        'Итоговые оценки за месяц':(20, 43, 87, 70),
        'Итоговая контрольная':70.2,
    }
}

In [137]:
# 1. Вывести ФИО всех учеников (по одному в каждой строке). Выводить через for
for k, v in group.items():
    print (v.get('Имя'), v.get('Фамилия'))

Иван Петров
Матвей Васильев
Татьяна Фоменко


In [138]:
# 2. Посчитать среднюю оценку по группе за каждый месяц (всего было 4 месяца - необходимо вывести 4 числа). 
# Опять же, делаем из предположения, что в словаре может быть очень большое кол-во записей.

def calculate_group_average(group):
    arr_marks = []
    for k, v in group.items():
        row = list(v.get('Итоговые оценки за месяц'))
        arr_marks.append(row)

    import numpy as np
    narr_marks = np.array(arr_marks)

    print (narr_marks)
    print ("Средние по месяцам группы: ", (narr_marks.mean(axis=0, dtype=int)))



In [139]:
calculate_group_average(group=group)

[[60 65 97 40]
 [70 75 67 40]
 [20 43 87 70]]
Средние по месяцам группы:  [50 61 83 50]


In [140]:
# Удалить ученика с самой низкой средней оценкой. 

# создание массива [телефон , средняя оценка]
arr = []
for k, v in group.items():
    row = (k, int(np.mean(list(v.get('Итоговые оценки за месяц')))))
    arr.append(row)


# перевод в словарь
dct = {telephone: average_mark for (telephone, average_mark) in arr}


# поиск минимальной оценка и соответствующего ключа в словаре
mi = 100
student = 'test'
for telephone, average_mark in dct.items():
    if average_mark < mi:
        mi = average_mark
        student = telephone
        
        
# удаление из group 
group.pop(student)




{'Имя': 'Татьяна',
 'Фамилия': 'Фоменко',
 'Пол': 'ж',
 'Дата рождения': '01-01-1988',
 'Возраст': 27,
 'Итоговые оценки за месяц': (20, 43, 87, 70),
 'Итоговая контрольная': 70.2}

In [141]:
# Посчитать п.2 по оставшимся.
calculate_group_average(group=group)

[[60 65 97 40]
 [70 75 67 40]]
Средние по месяцам группы:  [65 70 82 40]
