# Задача 1

Реализовать генератор, который разворачивает объекты типа `list()`, `str()` и `tuple()`, переданные в него.

Например, если передать в генератор список [3, 5, 6], то при итерировании он вернет элементы в следующем порядке: 6, 5, 4

In [1]:
def gen(obj):
    for i in range(1, len(obj) + 1):
        yield obj[-i]

In [2]:
for i in gen([3,5,6]):
    print(i)

6
5
3


In [3]:
for i in gen((3,5,6)):
    print(i)

6
5
3


In [4]:
for i in gen('356'):
    print(i)

6
5
3


# Задача 2

Вам дан двумерный массив

In [5]:
import numpy as np

In [6]:
a = np.array([[10, np.NaN, np.Inf, 3], [8, 10, -3, 1], 
              [1000, 0.5, 12, np.NaN], [1, 1, np.NaN, 3], 
              [0, np.Inf, 3, 3], [-1, -1, np.Inf, 10]], float)

In [7]:
a

array([[ 1.0e+01,      nan,      inf,  3.0e+00],
       [ 8.0e+00,  1.0e+01, -3.0e+00,  1.0e+00],
       [ 1.0e+03,  5.0e-01,  1.2e+01,      nan],
       [ 1.0e+00,  1.0e+00,      nan,  3.0e+00],
       [ 0.0e+00,      inf,  3.0e+00,  3.0e+00],
       [-1.0e+00, -1.0e+00,      inf,  1.0e+01]])

Ваша задача: 
1. С помощью встроенных в numpy средств подсчитать количество НЕ чисел (nan, inf) в каждой колонке. 
2. С помощью встроенных в numpy средств отфильтровать соответствующие колонки (где содержится хотя бы одно НЕ число).
3. В дополнение, отфильтровать все строки, в которых содержится хотя бы одно НЕ число).

In [8]:
for i in range(a.shape[1]):
    column = a[:, i]
    count_nan = np.isnan(column).sum()
    count_inf = np.isinf(column).sum()
    print ('колонка {}: количество nan: {}, количество inf: {}'.format(i, count_nan, count_inf))
      

колонка 0: количество nan: 0, количество inf: 0
колонка 1: количество nan: 1, количество inf: 1
колонка 2: количество nan: 1, количество inf: 2
колонка 3: количество nan: 1, количество inf: 0


In [9]:
# В дополнение, отфильтровать все строки, в которых содержится хотя бы одно НЕ число)
condition = np.all(~np.isnan(a), axis=1) & np.all(~np.isinf(a), axis=1)
#print(condition)
print(a[condition])

[[ 8. 10. -3.  1.]]


In [10]:
# С помощью встроенных в numpy средств отфильтровать соответствующие колонки 
#(где содержится хотя бы одно НЕ число).
x = a.transpose()
condition_1 = np.all(~np.isnan(x), axis=1) & np.all(~np.isinf(x), axis=1)
print(x[condition_1])


[[  10.    8. 1000.    1.    0.   -1.]]


# Задача 3

В приложении `spi_matches.csv` вам предоставлены данные по футбольным матчам.  
Вам необходимо считать файл стандартными средствами с помощью `open` или библиотеки `csv`  

Загрузить ТОЛЬКО колонки с числовыми значениями в матрицу `numpy`
Для колонок score1 и score2 (забитые голы командой хозяев и гостей) подсчитать среднее и медиану по всей выборке с помощью `numpy`. Выбор конкретной колонки так же необходимо реализовывать через средства `numpy`.
Какая из команд забивает в среднем больше? Хозяева или гости?

Отфильтровать матчи, в которых score1 == score2 (ничьи). Аналогично, подсчитать среднее и медиану кол-ва голов по выборке.

In [11]:
# import csv

In [51]:
# with open('spi_matches.csv', 'r') as file:    
#     matches = list(csv.reader(file))
#     matches = np.array(matches[1:])
    
#date, league_id, league, team1,       team2,             spi1,  spi2,  prob1, prob2,probtie,proj_score1,proj_score2,importance1,importance2,score1,score2,xg1, xg2, nsxg1,nsxg2,adj_score1,adj_score2
#2016-08-12,1843,French Ligue 1,Bastia,Paris Saint-Germain,51.16,85.68,0.0463,0.838, 0.1157,  0.91,      2.36,       32.4,       67.7,       0,     1,     0.97,0.63,0.43, 0.45, 0.0,       1.05
